// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gamjzzomkosvqhficabt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbWp6em9ta29zdnFoZmljYWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODc3MDAsImV4cCI6MjA2ODQ2MzcwMH0.r8KkywdhNSP1hxzSAlKo8SB5jOEb0KQRUBfZ9Va0p9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// D2 ve Burdon template'ler için localStorage'a config kaydet
if (typeof window !== 'undefined') {
  try {
    localStorage.setItem('sb-url', SUPABASE_URL);
    localStorage.setItem('sb-anon-key', SUPABASE_PUBLISHABLE_KEY);
    console.log('✅ Supabase config localStorage\'a kaydedildi');
  } catch (error) {
    console.warn('⚠️ localStorage\'a Supabase config kaydedilemedi:', error);
  }
}