// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// D2 ve Burdon template'ler için localStorage'a config kaydet
if (typeof window !== 'undefined') {
  try {
    localStorage.setItem('sb-url', SUPABASE_URL);
    localStorage.setItem('sb-anon-key', SUPABASE_PUBLISHABLE_KEY);
    console.log('✅ Supabase config localStorage\'a kaydedildi');
  } catch (error) {
    console.warn('⚠️ localStorage\'a Supabase config kaydedilemedi:', error);
  }
}